### ISSUE TITLE
Firefox for Android download points to outdated version

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/homepage#61]
The "Firefox for Android" download link on homepage links to ftp://ftp.mozilla.org/pub/mobile/releases/31.0/android/ which's v31.

It might be better to redirect to play store.

**Comment by foxt7ot** [comment]
Agreed, Is there any specific reason to not to point directly to google play. @debloper @kaustavdm

**Comment by pmjcreations** [comment]
I am supporting this. @debloper @kaustavdm can we link to [Google Play](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

**Comment by sagarhani** [comment]
Can't expect everyone to be on google play store. :confused: 
Updating the ftp link regularly would be the only solution I guess.

**Comment by pmjcreations** [comment]
Hello @sagarhani updating a link manually, based on every release will never gonna work.
The CTA is to download Firefox for Android and Google Play is the place where we release them  for our users.

**Comment by sagarhani** [comment]
Hey @pmjcreations, 
Okay fine. :+1: 
Let's link it to Google Play store. 
My concern was for those who don't have Google Play Store.

**Comment by foxt7ot** [comment]
@sagarhani Dunno about that much as I am no fan of android but AFAIK If a person is using an Android device, Then it's mandatory for that person to sign up for google services otherwise user will not be able to enjoy perks of using android, Am i right?

**Comment by sagarhani** [comment]
@foxt7ot Some don't like google services, so they don't use any google apps.
However, even the https://www.mozilla.org/en-US/firefox/android/ site links to google play store.
We can also point to the same. :+1:

**Comment by pmjcreations** [comment]
Interesting. @debloper I am backing my link suggestion to [Firefox for Android landing page](https://www.mozilla.org/en-US/firefox/android/) instead of Google Play with high priority.

**Comment by pmjcreations** [comment]
@foxt7ot Please use https://www.mozilla.org/en-US/firefox/android/ when you send your pull request.

**Comment by asdofindia** [comment]
Please avoid hard-coding the locale. mozilla.org automatically redirects to the appropriate locale when a user goes to locale-less links.
For example, https://www.mozilla.org/firefox/android/ will lead to https://www.mozilla.org/hi-IN/firefox/android/ if the user has hindi locale set in their browser. It'll fall back to en-US if the set locale isn't available.

Also, @sagarhani people who don't have play store in their android phone are usually the people who don't have difficulty in finding the link to a software they need. It's pointless to cater to them while losing out on the larger number of people.

**Comment by pmjcreations** [comment]
When we can see the changes reflected on http://mozillaindia.org/?

**Comment by asdofindia** [comment]
@pmjcreations I just filed #72 to automate deployments. Till that's fixed, the changes need to be manually synced to server and that'll take some time. A few days, maybe.

**Comment by pmjcreations** [comment]
@asdofindia Any updates on this? It's still not fixed
