### ISSUE TITLE
Uneven spacing inside carousel

### ISSUE THREAD

**Issue by shivamMg** [MozillaIndia/homepage#65]
[At mozillaindia.org] The carousel has unnecessary space between the images and upper border of the carousel-box. If someone gives a go-ahead, I would like to submit a patch.

**Comment by asdofindia** [comment]
Looks like there's indeed some space extra. I think it'll look good if the top and bottom have the same gap.

**Comment by shivamMg** [comment]
Alright, I will submit a PR with the fix.

**Comment by shivamMg** [comment]
@asdofindia PR submitted. You may review it. Seems like the homepage had two ids with same value (`main-content`).
