### ISSUE TITLE
There is no hyperlink to application form on Be MahaDev page

### ISSUE THREAD

**Issue by CuriousLearner** [MozillaIndia/homepage#77]
Refer here: devs.mozillaindia.org/start/

So, in the article itself, last paragraph has this:

> If you haven't done so already, fill this application form and one of us will get in touch with you.

But there is no hyper-link to be found for any application form.

**Comment by CuriousLearner** [comment]
Hi @asdofindia !

Can you have a look at this please :)

**Comment by InderdeepBajwa** [comment]
I'm also experiencing the same issue. Please let me know if you've already fond an issue to it.

**Comment by asdofindia** [comment]
Already known while merging mozillaindia/mozillaindia.github.io#5

Could you open this issue in that repository, though?
