### ISSUE TITLE
Grammatical error in Be MahaDev page.

### ISSUE THREAD

**Issue by theaverageguy** [MozillaIndia/homepage#78]
What is as of now:
" If all goes well, in some time, we'll have two people who know how to fix things and at least one with time to. "

What it should be:
"If all goes well, in some time, we'll have two people who know how to fix things and at least one with time too. "

**Comment by asdofindia** [comment]
This issue belongs to [a different repo](https://github.com/mozillaindia/mozillaindia.github.io). Yet, I think the sentence is like "...at least one with time to (fix things)"
